const LCARSColorPalette = {
  Yellow: "#ff9",
  Gold: "#fc6",
  Orange: "#f93",
  Purple: "#646",
  LightBlue: "#9cf",
  MarineBlue: "#36c",
  BahamaBlue: "#069",
  RedAlert: "#e10",
  White: "#fff",
  PurpleBlue: "#99c",
  Lavender: "#97a",
  LightLavender: "#99f",
  Lilac: "#c9c",
  Pink: "#c69",
  Chestnut: "#c66",
  OrangePeel: "#f96",
  Tangerine: "#f90",
  Gray: "#234",
  GrayBlue: "#68c",
  Indigo: "#45b",
  Cosmic: "#746",
  RedSand: "#d64",
  Caramel: "#a53",
  Burbon: "#b62",
  Sand: "#e95",
  WhiteBlue: "#cdf",
  DodgerBlue: "#59f",
  DodgerBlueAlt: "#36f",
  Blue: "#01e",
  NavyBlue: "#008",
  Olive: "#ba5",
  Rust: "#b41",
  RedBrown: "#821",
};

export default LCARSColorPalette;
