export const LCARSColorPalette = {
  StandardOrange: "#ff9c00",
  StandardOcca: "#f7b05a",
  StandardBeige: "#ffcc99",
  StandardYellow: "#ffff33",
  StandardLightYellow: "#ffff9c",
  StandardMagenta: "#cd6363",
  StandardPurple: "#cc99cc",
  StandardLightOrange: "#ffcc99",
  StandardBlue: "#646dcc",
  StandardLightBlue: "#9c9cff",
  StandardTurquoise: "#3399ff",
  StandardLightTurquoise: "#99ccff",
  StandardSand: "#ffffcc",
  StandardDirt: "#b1957a",
  StandardMediumOrange: "#E0884c",
  StandardDarkYellow: "#f5ed00",
  StandardWhite: "#ddffff",
  RedAlert1: "#f5173c",
  RedAlert2: "#a30e24",
  RedAlert3: "#bf2d24",
  RedAlert4: "#f5173c",
  RedAlert5: "#bf2d42",
};
